/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

public void imgTogButton2_click1(GImageToggleButton source, GEvent event) { //_CODE_:imgTogButton2:721181:
  println("imgTogButton2 - GImageToggleButton event occured " + System.currentTimeMillis()%10000000 );
} //_CODE_:imgTogButton2:721181:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setCursor(ARROW);
  if(frame != null)
    frame.setTitle("Sketch Window");
  imgTogButton2 = new GImageToggleButton(this, 341, 179);
  imgTogButton2.addEventHandler(this, "imgTogButton2_click1");
  label1 = new GLabel(this, 341, 153, 40, 20);
  label1.setText("RUN");
  label1.setOpaque(false);
}

// Variable declarations 
// autogenerated do not edit
GImageToggleButton imgTogButton2; 
GLabel label1; 

